# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kimth/bloominho/vivado/DMA_32bits/DMA_32bits.srcs/sources_1/ip/bram/bram.xci
# IP: The module: 'bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kimth/bloominho/vivado/DMA_32bits/DMA_32bits.gen/sources_1/ip/bram/bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/kimth/bloominho/vivado/DMA_32bits/DMA_32bits.srcs/sources_1/ip/bram/bram.xci
# IP: The module: 'bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kimth/bloominho/vivado/DMA_32bits/DMA_32bits.gen/sources_1/ip/bram/bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
