transcript off
onbreak {quit -force}
onerror {quit -force}
transcript on

vlib work
vmap -link {}
vlib activehdl/xilinx_vip
vlib activehdl/xpm
vlib activehdl/axi_infrastructure_v1_1_0
vlib activehdl/axi_vip_v1_1_14
vlib activehdl/processing_system7_vip_v1_0_16
vlib activehdl/xil_defaultlib
vlib activehdl/lib_pkg_v1_0_2
vlib activehdl/fifo_generator_v13_2_8
vlib activehdl/lib_fifo_v1_0_17
vlib activehdl/lib_srl_fifo_v1_0_2
vlib activehdl/lib_cdc_v1_0_2
vlib activehdl/axi_datamover_v5_1_30
vlib activehdl/axi_sg_v4_1_16
vlib activehdl/axi_dma_v7_1_29
vlib activehdl/proc_sys_reset_v5_0_13
vlib activehdl/generic_baseblocks_v2_1_0
vlib activehdl/axi_register_slice_v2_1_28
vlib activehdl/axi_data_fifo_v2_1_27
vlib activehdl/axi_crossbar_v2_1_29
vlib activehdl/gigantic_mux
vlib activehdl/axis_infrastructure_v1_1_0
vlib activehdl/axis_data_fifo_v2_0_10
vlib activehdl/axi_protocol_converter_v2_1_28
vlib activehdl/axi_clock_converter_v2_1_27
vlib activehdl/blk_mem_gen_v8_4_6
vlib activehdl/axi_dwidth_converter_v2_1_28

vlog -work xilinx_vip  -sv2k12 "+incdir+/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l lib_pkg_v1_0_2 -l fifo_generator_v13_2_8 -l lib_fifo_v1_0_17 -l lib_srl_fifo_v1_0_2 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_30 -l axi_sg_v4_1_16 -l axi_dma_v7_1_29 -l proc_sys_reset_v5_0_13 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l gigantic_mux -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_protocol_converter_v2_1_28 -l axi_clock_converter_v2_1_27 -l blk_mem_gen_v8_4_6 -l axi_dwidth_converter_v2_1_28 \
"/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
"/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
"/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm  -sv2k12 "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/1b7e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/122e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/affe/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/20d0/hdl/verilog" "+incdir+/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l lib_pkg_v1_0_2 -l fifo_generator_v13_2_8 -l lib_fifo_v1_0_17 -l lib_srl_fifo_v1_0_2 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_30 -l axi_sg_v4_1_16 -l axi_dma_v7_1_29 -l proc_sys_reset_v5_0_13 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l gigantic_mux -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_protocol_converter_v2_1_28 -l axi_clock_converter_v2_1_27 -l blk_mem_gen_v8_4_6 -l axi_dwidth_converter_v2_1_28 \
"/home/kimth/tools/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"/home/kimth/tools/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"/home/kimth/tools/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93  \
"/home/kimth/tools/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work axi_infrastructure_v1_1_0  -v2k5 "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/1b7e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/122e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/affe/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/20d0/hdl/verilog" "+incdir+/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l lib_pkg_v1_0_2 -l fifo_generator_v13_2_8 -l lib_fifo_v1_0_17 -l lib_srl_fifo_v1_0_2 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_30 -l axi_sg_v4_1_16 -l axi_dma_v7_1_29 -l proc_sys_reset_v5_0_13 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l gigantic_mux -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_protocol_converter_v2_1_28 -l axi_clock_converter_v2_1_27 -l blk_mem_gen_v8_4_6 -l axi_dwidth_converter_v2_1_28 \
"../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_14  -sv2k12 "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/1b7e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/122e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/affe/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/20d0/hdl/verilog" "+incdir+/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l lib_pkg_v1_0_2 -l fifo_generator_v13_2_8 -l lib_fifo_v1_0_17 -l lib_srl_fifo_v1_0_2 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_30 -l axi_sg_v4_1_16 -l axi_dma_v7_1_29 -l proc_sys_reset_v5_0_13 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l gigantic_mux -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_protocol_converter_v2_1_28 -l axi_clock_converter_v2_1_27 -l blk_mem_gen_v8_4_6 -l axi_dwidth_converter_v2_1_28 \
"../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ed63/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work processing_system7_vip_v1_0_16  -sv2k12 "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/1b7e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/122e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/affe/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/20d0/hdl/verilog" "+incdir+/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l lib_pkg_v1_0_2 -l fifo_generator_v13_2_8 -l lib_fifo_v1_0_17 -l lib_srl_fifo_v1_0_2 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_30 -l axi_sg_v4_1_16 -l axi_dma_v7_1_29 -l proc_sys_reset_v5_0_13 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l gigantic_mux -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_protocol_converter_v2_1_28 -l axi_clock_converter_v2_1_27 -l blk_mem_gen_v8_4_6 -l axi_dwidth_converter_v2_1_28 \
"../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/aed8/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/1b7e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/122e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/affe/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/20d0/hdl/verilog" "+incdir+/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l lib_pkg_v1_0_2 -l fifo_generator_v13_2_8 -l lib_fifo_v1_0_17 -l lib_srl_fifo_v1_0_2 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_30 -l axi_sg_v4_1_16 -l axi_dma_v7_1_29 -l proc_sys_reset_v5_0_13 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l gigantic_mux -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_protocol_converter_v2_1_28 -l axi_clock_converter_v2_1_27 -l blk_mem_gen_v8_4_6 -l axi_dwidth_converter_v2_1_28 \
"../../../bd/system/ip/system_processing_system7_0_0/sim/system_processing_system7_0_0.v" \

vcom -work lib_pkg_v1_0_2 -93  \
"../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \

vlog -work fifo_generator_v13_2_8  -v2k5 "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/1b7e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/122e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/affe/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/20d0/hdl/verilog" "+incdir+/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l lib_pkg_v1_0_2 -l fifo_generator_v13_2_8 -l lib_fifo_v1_0_17 -l lib_srl_fifo_v1_0_2 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_30 -l axi_sg_v4_1_16 -l axi_dma_v7_1_29 -l proc_sys_reset_v5_0_13 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l gigantic_mux -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_protocol_converter_v2_1_28 -l axi_clock_converter_v2_1_27 -l blk_mem_gen_v8_4_6 -l axi_dwidth_converter_v2_1_28 \
"../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/c97d/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_2_8 -93  \
"../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/c97d/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -work fifo_generator_v13_2_8  -v2k5 "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/1b7e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/122e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/affe/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/20d0/hdl/verilog" "+incdir+/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l lib_pkg_v1_0_2 -l fifo_generator_v13_2_8 -l lib_fifo_v1_0_17 -l lib_srl_fifo_v1_0_2 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_30 -l axi_sg_v4_1_16 -l axi_dma_v7_1_29 -l proc_sys_reset_v5_0_13 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l gigantic_mux -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_protocol_converter_v2_1_28 -l axi_clock_converter_v2_1_27 -l blk_mem_gen_v8_4_6 -l axi_dwidth_converter_v2_1_28 \
"../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/c97d/hdl/fifo_generator_v13_2_rfs.v" \

vcom -work lib_fifo_v1_0_17 -93  \
"../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/3d41/hdl/lib_fifo_v1_0_rfs.vhd" \

vcom -work lib_srl_fifo_v1_0_2 -93  \
"../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \

vcom -work lib_cdc_v1_0_2 -93  \
"../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work axi_datamover_v5_1_30 -93  \
"../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/e959/hdl/axi_datamover_v5_1_vh_rfs.vhd" \

vcom -work axi_sg_v4_1_16 -93  \
"../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/85d0/hdl/axi_sg_v4_1_rfs.vhd" \

vcom -work axi_dma_v7_1_29 -93  \
"../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/50c3/hdl/axi_dma_v7_1_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  \
"../../../bd/system/ip/system_axi_dma_0_0/sim/system_axi_dma_0_0.vhd" \

vcom -work proc_sys_reset_v5_0_13 -93  \
"../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  \
"../../../bd/system/ip/system_rst_ps7_0_50M_0/sim/system_rst_ps7_0_50M_0.vhd" \

vlog -work generic_baseblocks_v2_1_0  -v2k5 "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/1b7e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/122e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/affe/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/20d0/hdl/verilog" "+incdir+/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l lib_pkg_v1_0_2 -l fifo_generator_v13_2_8 -l lib_fifo_v1_0_17 -l lib_srl_fifo_v1_0_2 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_30 -l axi_sg_v4_1_16 -l axi_dma_v7_1_29 -l proc_sys_reset_v5_0_13 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l gigantic_mux -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_protocol_converter_v2_1_28 -l axi_clock_converter_v2_1_27 -l blk_mem_gen_v8_4_6 -l axi_dwidth_converter_v2_1_28 \
"../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_28  -v2k5 "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/1b7e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/122e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/affe/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/20d0/hdl/verilog" "+incdir+/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l lib_pkg_v1_0_2 -l fifo_generator_v13_2_8 -l lib_fifo_v1_0_17 -l lib_srl_fifo_v1_0_2 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_30 -l axi_sg_v4_1_16 -l axi_dma_v7_1_29 -l proc_sys_reset_v5_0_13 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l gigantic_mux -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_protocol_converter_v2_1_28 -l axi_clock_converter_v2_1_27 -l blk_mem_gen_v8_4_6 -l axi_dwidth_converter_v2_1_28 \
"../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/87d1/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work axi_data_fifo_v2_1_27  -v2k5 "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/1b7e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/122e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/affe/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/20d0/hdl/verilog" "+incdir+/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l lib_pkg_v1_0_2 -l fifo_generator_v13_2_8 -l lib_fifo_v1_0_17 -l lib_srl_fifo_v1_0_2 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_30 -l axi_sg_v4_1_16 -l axi_dma_v7_1_29 -l proc_sys_reset_v5_0_13 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l gigantic_mux -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_protocol_converter_v2_1_28 -l axi_clock_converter_v2_1_27 -l blk_mem_gen_v8_4_6 -l axi_dwidth_converter_v2_1_28 \
"../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/fab7/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_crossbar_v2_1_29  -v2k5 "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/1b7e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/122e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/affe/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/20d0/hdl/verilog" "+incdir+/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l lib_pkg_v1_0_2 -l fifo_generator_v13_2_8 -l lib_fifo_v1_0_17 -l lib_srl_fifo_v1_0_2 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_30 -l axi_sg_v4_1_16 -l axi_dma_v7_1_29 -l proc_sys_reset_v5_0_13 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l gigantic_mux -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_protocol_converter_v2_1_28 -l axi_clock_converter_v2_1_27 -l blk_mem_gen_v8_4_6 -l axi_dwidth_converter_v2_1_28 \
"../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/f8f3/hdl/axi_crossbar_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/1b7e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/122e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/affe/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/20d0/hdl/verilog" "+incdir+/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l lib_pkg_v1_0_2 -l fifo_generator_v13_2_8 -l lib_fifo_v1_0_17 -l lib_srl_fifo_v1_0_2 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_30 -l axi_sg_v4_1_16 -l axi_dma_v7_1_29 -l proc_sys_reset_v5_0_13 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l gigantic_mux -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_protocol_converter_v2_1_28 -l axi_clock_converter_v2_1_27 -l blk_mem_gen_v8_4_6 -l axi_dwidth_converter_v2_1_28 \
"../../../bd/system/ip/system_xbar_0/sim/system_xbar_0.v" \
"../../../bd/system/ip/system_system_ila_0_0/bd_0/sim/bd_d5b8.v" \
"../../../bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_0/sim/bd_d5b8_ila_lib_0.v" \

vlog -work gigantic_mux  -v2k5 "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/1b7e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/122e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/affe/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/20d0/hdl/verilog" "+incdir+/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l lib_pkg_v1_0_2 -l fifo_generator_v13_2_8 -l lib_fifo_v1_0_17 -l lib_srl_fifo_v1_0_2 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_30 -l axi_sg_v4_1_16 -l axi_dma_v7_1_29 -l proc_sys_reset_v5_0_13 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l gigantic_mux -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_protocol_converter_v2_1_28 -l axi_clock_converter_v2_1_27 -l blk_mem_gen_v8_4_6 -l axi_dwidth_converter_v2_1_28 \
"../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/e87a/hdl/gigantic_mux_v1_0_cntr.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/1b7e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/122e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/affe/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/20d0/hdl/verilog" "+incdir+/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l lib_pkg_v1_0_2 -l fifo_generator_v13_2_8 -l lib_fifo_v1_0_17 -l lib_srl_fifo_v1_0_2 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_30 -l axi_sg_v4_1_16 -l axi_dma_v7_1_29 -l proc_sys_reset_v5_0_13 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l gigantic_mux -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_protocol_converter_v2_1_28 -l axi_clock_converter_v2_1_27 -l blk_mem_gen_v8_4_6 -l axi_dwidth_converter_v2_1_28 \
"../../../bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_1/bd_d5b8_g_inst_0_gigantic_mux.v" \
"../../../bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_1/sim/bd_d5b8_g_inst_0.v" \
"../../../bd/system/ip/system_system_ila_0_0/sim/system_system_ila_0_0.v" \

vlog -work axis_infrastructure_v1_1_0  -v2k5 "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/1b7e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/122e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/affe/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/20d0/hdl/verilog" "+incdir+/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l lib_pkg_v1_0_2 -l fifo_generator_v13_2_8 -l lib_fifo_v1_0_17 -l lib_srl_fifo_v1_0_2 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_30 -l axi_sg_v4_1_16 -l axi_dma_v7_1_29 -l proc_sys_reset_v5_0_13 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l gigantic_mux -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_protocol_converter_v2_1_28 -l axi_clock_converter_v2_1_27 -l blk_mem_gen_v8_4_6 -l axi_dwidth_converter_v2_1_28 \
"../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \

vlog -work axis_data_fifo_v2_0_10  -v2k5 "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/1b7e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/122e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/affe/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/20d0/hdl/verilog" "+incdir+/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l lib_pkg_v1_0_2 -l fifo_generator_v13_2_8 -l lib_fifo_v1_0_17 -l lib_srl_fifo_v1_0_2 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_30 -l axi_sg_v4_1_16 -l axi_dma_v7_1_29 -l proc_sys_reset_v5_0_13 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l gigantic_mux -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_protocol_converter_v2_1_28 -l axi_clock_converter_v2_1_27 -l blk_mem_gen_v8_4_6 -l axi_dwidth_converter_v2_1_28 \
"../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8eca/hdl/axis_data_fifo_v2_0_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/1b7e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/122e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/affe/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/20d0/hdl/verilog" "+incdir+/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l lib_pkg_v1_0_2 -l fifo_generator_v13_2_8 -l lib_fifo_v1_0_17 -l lib_srl_fifo_v1_0_2 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_30 -l axi_sg_v4_1_16 -l axi_dma_v7_1_29 -l proc_sys_reset_v5_0_13 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l gigantic_mux -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_protocol_converter_v2_1_28 -l axi_clock_converter_v2_1_27 -l blk_mem_gen_v8_4_6 -l axi_dwidth_converter_v2_1_28 \
"../../../bd/system/ip/system_axis_data_fifo_0_0/sim/system_axis_data_fifo_0_0.v" \
"../../../bd/system/ip/system_system_ila_0_1/bd_0/sim/bd_1579.v" \
"../../../bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_0/sim/bd_1579_ila_lib_0.v" \
"../../../bd/system/ip/system_system_ila_0_1/sim/system_system_ila_0_1.v" \

vlog -work axi_protocol_converter_v2_1_28  -v2k5 "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/1b7e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/122e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/affe/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/20d0/hdl/verilog" "+incdir+/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l lib_pkg_v1_0_2 -l fifo_generator_v13_2_8 -l lib_fifo_v1_0_17 -l lib_srl_fifo_v1_0_2 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_30 -l axi_sg_v4_1_16 -l axi_dma_v7_1_29 -l proc_sys_reset_v5_0_13 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l gigantic_mux -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_protocol_converter_v2_1_28 -l axi_clock_converter_v2_1_27 -l blk_mem_gen_v8_4_6 -l axi_dwidth_converter_v2_1_28 \
"../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8c02/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/1b7e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/122e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/affe/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/20d0/hdl/verilog" "+incdir+/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l lib_pkg_v1_0_2 -l fifo_generator_v13_2_8 -l lib_fifo_v1_0_17 -l lib_srl_fifo_v1_0_2 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_30 -l axi_sg_v4_1_16 -l axi_dma_v7_1_29 -l proc_sys_reset_v5_0_13 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l gigantic_mux -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_protocol_converter_v2_1_28 -l axi_clock_converter_v2_1_27 -l blk_mem_gen_v8_4_6 -l axi_dwidth_converter_v2_1_28 \
"../../../bd/system/ip/system_auto_pc_0/sim/system_auto_pc_0.v" \

vlog -work axi_clock_converter_v2_1_27  -v2k5 "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/1b7e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/122e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/affe/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/20d0/hdl/verilog" "+incdir+/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l lib_pkg_v1_0_2 -l fifo_generator_v13_2_8 -l lib_fifo_v1_0_17 -l lib_srl_fifo_v1_0_2 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_30 -l axi_sg_v4_1_16 -l axi_dma_v7_1_29 -l proc_sys_reset_v5_0_13 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l gigantic_mux -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_protocol_converter_v2_1_28 -l axi_clock_converter_v2_1_27 -l blk_mem_gen_v8_4_6 -l axi_dwidth_converter_v2_1_28 \
"../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/29db/hdl/axi_clock_converter_v2_1_vl_rfs.v" \

vlog -work blk_mem_gen_v8_4_6  -v2k5 "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/1b7e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/122e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/affe/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/20d0/hdl/verilog" "+incdir+/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l lib_pkg_v1_0_2 -l fifo_generator_v13_2_8 -l lib_fifo_v1_0_17 -l lib_srl_fifo_v1_0_2 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_30 -l axi_sg_v4_1_16 -l axi_dma_v7_1_29 -l proc_sys_reset_v5_0_13 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l gigantic_mux -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_protocol_converter_v2_1_28 -l axi_clock_converter_v2_1_27 -l blk_mem_gen_v8_4_6 -l axi_dwidth_converter_v2_1_28 \
"../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/bb55/simulation/blk_mem_gen_v8_4.v" \

vlog -work axi_dwidth_converter_v2_1_28  -v2k5 "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/1b7e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/122e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/affe/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/20d0/hdl/verilog" "+incdir+/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l lib_pkg_v1_0_2 -l fifo_generator_v13_2_8 -l lib_fifo_v1_0_17 -l lib_srl_fifo_v1_0_2 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_30 -l axi_sg_v4_1_16 -l axi_dma_v7_1_29 -l proc_sys_reset_v5_0_13 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l gigantic_mux -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_protocol_converter_v2_1_28 -l axi_clock_converter_v2_1_27 -l blk_mem_gen_v8_4_6 -l axi_dwidth_converter_v2_1_28 \
"../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/08ae/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/1b7e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/122e/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/affe/hdl/verilog" "+incdir+../../../../NDP_2stage.gen/sources_1/bd/system/ipshared/20d0/hdl/verilog" "+incdir+/home/kimth/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l lib_pkg_v1_0_2 -l fifo_generator_v13_2_8 -l lib_fifo_v1_0_17 -l lib_srl_fifo_v1_0_2 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_30 -l axi_sg_v4_1_16 -l axi_dma_v7_1_29 -l proc_sys_reset_v5_0_13 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l gigantic_mux -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_protocol_converter_v2_1_28 -l axi_clock_converter_v2_1_27 -l blk_mem_gen_v8_4_6 -l axi_dwidth_converter_v2_1_28 \
"../../../bd/system/ip/system_auto_us_0/sim/system_auto_us_0.v" \
"../../../bd/system/ip/system_auto_us_1/sim/system_auto_us_1.v" \
"../../../bd/system/ip/system_auto_us_2/sim/system_auto_us_2.v" \
"../../../bd/system/ip/system_auto_pc_1/sim/system_auto_pc_1.v" \
"../../../bd/system/sim/system.v" \

vlog -work xil_defaultlib \
"glbl.v"

