set_property SRC_FILE_INFO {cfile:/home/kimth/bloominho/systolic_array/synth/zc706_r1.0.ucf.xdc rfile:../../../../../systolic_array/synth/zc706_r1.0.ucf.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H9 [get_ports SYSCLK_P]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [get_ports SYSCLK_P]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G9 [get_ports SYSCLK_N]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [get_ports SYSCLK_N]
